feat: Dto 설정, FeelingPostController 생성 -#10
Google-Developer-Student-Club-Hanyang/today-feeling-backend-2- pull request #11
Opened 2023-03-08 14:47 UTC by wimmings

# feat: Dto 설정, FeelingPostController 생성 -#10

### 변경 사항

1. Service에서 Entity 대신 requestDto, responseDto 사용했습니다.
2. FeelingPostController 쪽 생성했습니다.
3. ClinicHeart 쪽에도 BaseTimeEntity 추가했습니다.

<br/>
+ 이 PR 도중에 db 관련 답을 받았습니다..! 이 부분은 한꺼번에 수정하여 올리겠습니다

<br/>

closed #10

2023-03-10 15:55 UTC, grand7070 requested changes

2023-03-10 15:55 UTC, grand7070 commented on src/main/java/com/gdschanyang/todayfeelingbackend2/controller/IndexController.java
> +        return "home";
이건 왜 있는건가요? 저희는 REST API여서 이런 API는 사용하지 않습니다

2023-03-10 15:55 UTC, grand7070 commented on src/main/java/com/gdschanyang/todayfeelingbackend2/domain/hearts/ClinicHeart.java
> +    public ClinicHeart() {
빈 생성자를 만드셨는데 ClinicHeart가 생성될때 user와 clinicpost 값을 받아야 하므로 두 필드를 받는 생성자를 만드셔야 합니다.

@Builder
public ClinicHeart(User user, ClinicPost clinicPost)  {
  this.user = user;
  this.clinicPost = clinicPost;
  ...
}

2023-03-10 15:55 UTC, grand7070 commented on src/main/java/com/gdschanyang/todayfeelingbackend2/domain/posts/FeelingPost.java
> +    private char delFlag;
DB에서는 String으로 보여지는게 맞지만 어플리케이션 내 객체로는 boolean이 맞습니다. JPA가 DB에 종속적이지 않은 객체 중심 개발을 위해 만들어진 것이므로 Boolean으로 사용하시는게 좋을 것 같습니다

2023-03-10 15:55 UTC, grand7070 commented on src/main/java/com/gdschanyang/todayfeelingbackend2/domain/posts/FeelingPost.java
> +    private List<FeelingHeart> feelingHearts = new ArrayList<FeelingHeart>();
new ArrayList<>(); 로 <>안의 제네릭을 생략할 수 있습니다

2023-03-11 04:13 UTC, wimmings commented on src/main/java/com/gdschanyang/todayfeelingbackend2/controller/IndexController.java
> +        return "home";
아하 넵 수정하겠습니다!

2023-03-11 04:14 UTC, wimmings commented on src/main/java/com/gdschanyang/todayfeelingbackend2/domain/hearts/ClinicHeart.java
> +    public ClinicHeart() {
앗 넵!! 클리닉부분에 살짝 미스가 났습니다 바로 수정하겠습니다!

2023-03-11 04:14 UTC, wimmings commented on src/main/java/com/gdschanyang/todayfeelingbackend2/domain/posts/FeelingPost.java
> +    private char delFlag;
넵! 슬랙에 올려주신 것 참고하여 수정했습니다 감사합니다 :)

2023-03-11 04:15 UTC, wimmings commented on src/main/java/com/gdschanyang/todayfeelingbackend2/domain/posts/FeelingPost.java
> +    private List<FeelingHeart> feelingHearts = new ArrayList<FeelingHeart>();
넵!!

2023-03-13 07:44 UTC, closed without merging