refactor : Entity 구조 재설정
Google-Developer-Student-Club-Hanyang/today-feeling-backend-2- pull request #5
Opened 2023-02-19 06:26 UTC by wimmings

# refactor: Entity 구조 재설정 -#4

### 변경 사항

1. 엔티티, 테이블 구조를 재설정 하였습니다.
    유저 : 감정글 = 1 : 1

    감정공감글 : 유저 = 1 : N
    감정공감글 : 감정글 = 1 : N

    클리닉공감글 : 유저 = 1 : N
    클리닉공감글 : 클리닉글 = 1 : N

으로 설정하였습니다.

2. 불필요한 복수형은 모두 단수형으로 바꾸었습니다.
3. 감정을 긍/부정으로 구성하였습니다.
4. User 정보에 본명과 닉네임을 두어서 대나무숲과 클리닉 센터에서는 닉네임을 쓰도록 민기님과 상의하여 결정하였습니다.
5. 감정글에 제목을 없애고, 삭제 여부를 추가하였습니다.
<br/>

### 참고 사항

- 리뷰어가 참고할 수 있는 내용 1

<br/>

closed #4

2023-02-19 12:24 UTC, grand7070 requested changes

2023-02-19 12:43 UTC, wimmings commented
아 {}부분은 깜빡하고 못 지웠습니다. 다음에 유의하겠습니다

2023-02-19 12:44 UTC, wimmings commented on src/main/java/com/gdschanyang/todayfeelingbackend2/domain/hearts/ClinicHeart.java
> +    // 공감한 유저, 공감한 클리닉 글
넵 알겠습니다 !

2023-02-19 12:46 UTC, kuku-kun commented on src/main/java/com/gdschanyang/todayfeelingbackend2/domain/hearts/ClinicHeart.java
> +    @Id
죄송합니다. 잠시 착오가 있었던 것 같습니다

2023-02-19 12:47 UTC, wimmings commented on src/main/java/com/gdschanyang/todayfeelingbackend2/domain/posts/ClinicPost.java
> +    @OneToOne
아하 넵 헷갈렸던 부분이 많았습니다.. 수정하겠습니다

2023-02-19 12:51 UTC, kuku-kun commented on src/main/java/com/gdschanyang/todayfeelingbackend2/domain/user/User.java
> +    // 본명
홈화면에 본명을 작성해야 한다고 생각하여 만들었습니다. 현재 닉네임만 만들었습니다

2023-02-19 12:59 UTC, kuku-kun commented on src/main/java/com/gdschanyang/todayfeelingbackend2/domain/hearts/ClinicHeart.java
> +    @JoinColumn(name = "CLINIC_HEART_USER")
현재 책을 보며 OneToMany일 때, mappedBy를 통해 묶는 걸 확인했습니다. 아직 연관관계에 대해서 명확하게 알지 못해 자주 보이는 방식으로 작성하다보니 JoinColumn을 사용하게 되었습니다.
그리고 name의 작명은 유저가 누른 공감이라는 의미로 객체가 좀 더 어떤 것인지 명확하게 알아보고자 작성하게 되었습니다.

2023-02-19 13:04 UTC, wimmings commented on src/main/java/com/gdschanyang/todayfeelingbackend2/domain/hearts/ClinicHeart.java
> +    @OneToMany
아하 이해했습니다..! 꼼꼼하게 봐주셔서 감사합니다ㅠ 저희가 이해하고 적용하는데 조금 시간이 걸렸네요,,!

2023-02-19 13:06 UTC, kuku-kun commented on src/main/java/com/gdschanyang/todayfeelingbackend2/domain/hearts/ClinicHeart.java
> +    @OneToMany
그러면 여러 개를 작성할 수 있는 영역이 n이 되는 건가요?
공감한 글같은 경우, 글에서 여러 개의 공감한 글을 꺼낼 수 있으니 1:n으로 봐야한다고 생각하는데 제 생각이 옳은지 모르겠습니다

2023-02-19 13:50 UTC, grand7070 commented on src/main/java/com/gdschanyang/todayfeelingbackend2/domain/hearts/ClinicHeart.java
> +    @OneToMany
아닙니다 이제 처음 하시는데요 그럴 수 있습니다
넵 맞습니다. 글 하나에 대해서 여러 개의 공감한 글이 생길 수 있으니 글과 공감한 글은 1:n입니다
사실 그 전에 유저와 글은 공감에 대해서 n:m 관계인데 @ManyToMany는 지양하므로 n:m 관계는 1:n, n:1로 나눠서 별도의 테이블을 만듭니다. 여기서는 이 별도의 테이블이 공감한 글이라는 테이블입니다

2023-02-21 06:15 UTC, closed without merging

2023-02-21 06:15 UTC, wimmings commented
코드 다시 작성하여 PR하겠습니다