feat: Setter 제거, BaseTimeEntity 추가, FeelingPostService 생성 -#7
Google-Developer-Student-Club-Hanyang/today-feeling-backend-2- pull request #8
Opened 2023-03-05 06:13 UTC by wimmings

# feat: Setter 제거, BaseTimeEntity 추가, FeelingPostService 생성 -#7

### 변경 사항

-저는 감정글쓰기, 대나무 숲을 맡았고, **감정 글쓰기(FeelingPost)** 부분 처리중입니다!

1. 편의함수에서 setter 제거하고 다 쪽에서 생성자를 이용했습니다.
2. BaseTimeEntity 생성하여 FeelingPost가 상속받도록 했습니다.
3. FeelingPostService 에서 save, update, findById, delete 기능 만들었습니다.

<br/>

### 참고 사항

이 레포지토리에 develop 브랜치 만들어서 이 곳에 푸시했습니다

<br/>

closed #7

2023-03-05 08:05 UTC, grand7070 requested changes

2023-03-05 08:05 UTC, grand7070 commented on src/main/java/com/gdschanyang/todayfeelingbackend2/domain/hearts/ClinicHeart.java
> +public class ClinicHeart {
BaseTimeEntity 만드셨으니 사용하시면 좋을 것 같습니다

2023-03-05 08:05 UTC, grand7070 commented on src/main/java/com/gdschanyang/todayfeelingbackend2/domain/hearts/ClinicHeart.java
> +    public ClinicHeart() {
기본 생성자를 만드셔서 해당 Entity에 필요한 필드값 (User, ClinicPost)들이 들어갈 수 없습니다
@NoArgsConstructor와 @AllArgsConstructor를 알아보시면 될 것 같습니다

2023-03-05 08:05 UTC, grand7070 commented on src/main/java/com/gdschanyang/todayfeelingbackend2/domain/posts/ClinicPost.java
> +    @OneToMany(mappedBy = "clinicPost")
1대다 양방향과 1대다 단방향에 대해 좀 더 알아보시면 좋을 것 같습니다. 이건 구현 방식 차이여서 옳고 그른 건 없습니다

2023-03-05 08:05 UTC, grand7070 commented on src/main/java/com/gdschanyang/todayfeelingbackend2/domain/posts/FeelingPost.java
> +    private boolean delFlag; //다시
DB에 1과 0으로 되어 있으면 알아보기 어렵습니다. True, False로 나타내는게 더 직관적입니다. 1과 0으로 저장되지 않고 True와 False로 저장되게 하는 방법이 있으므로 알아보시면 좋을 것 같습니다

2023-03-05 08:05 UTC, grand7070 commented on src/main/java/com/gdschanyang/todayfeelingbackend2/service/FeelingPostService.java
> +    public FeelingPostService(FeelingPostRepository feelingPostRepository) {
@RequiredArgsConstructor 알아보시면 좋을 것 같습니다

2023-03-05 12:50 UTC, wimmings commented on src/main/java/com/gdschanyang/todayfeelingbackend2/domain/hearts/ClinicHeart.java
> +public class ClinicHeart {
네! Clinic 부분 민기님께 전달하겠습니다

2023-03-05 12:50 UTC, wimmings commented on src/main/java/com/gdschanyang/todayfeelingbackend2/domain/hearts/ClinicHeart.java
> +    public ClinicHeart() {
아하 그렇군요..! 네! 해당 부분 더 공부하겠습니다!

2023-03-05 12:51 UTC, wimmings commented on src/main/java/com/gdschanyang/todayfeelingbackend2/domain/posts/ClinicPost.java
> +    @OneToMany(mappedBy = "clinicPost")
넵 이 부분도 다시 꼼꼼히 확인하겠습니다.!

2023-03-05 12:51 UTC, wimmings commented on src/main/java/com/gdschanyang/todayfeelingbackend2/domain/posts/FeelingPost.java
> +    private boolean delFlag; //다시
네! 알아보고 수정하겠습니다 감사합니다

2023-03-05 12:51 UTC, wimmings commented on src/main/java/com/gdschanyang/todayfeelingbackend2/service/FeelingPostService.java
> +    public FeelingPostService(FeelingPostRepository feelingPostRepository) {
네 감사합니다 :)

2023-03-06 06:12 UTC, kuku-kun commented on src/main/java/com/gdschanyang/todayfeelingbackend2/service/FeelingPostService.java
> +    public FeelingPostService(FeelingPostRepository feelingPostRepository) {
네, 감사합니다

2023-03-06 06:12 UTC, kuku-kun commented on src/main/java/com/gdschanyang/todayfeelingbackend2/domain/posts/FeelingPost.java
> +    private boolean delFlag; //다시
T/F로 저장되도록 수정하겠습니다. 감사합니다

2023-03-06 06:13 UTC, kuku-kun commented on src/main/java/com/gdschanyang/todayfeelingbackend2/domain/posts/ClinicPost.java
> +    @OneToMany(mappedBy = "clinicPost")
네, 감사합니다

2023-03-08 14:37 UTC, closed without merging